### ISSUE TITLE
Sticky Header Blocking Quickview

### ISSUE THREAD

**Issue by nickleow** [scriptcoil/oceanwp-sticky-header#11]
As shown in the image attached, the sticky header is blocking product quick view, currently using OceanWP theme with official Store demo.

![image](https://user-images.githubusercontent.com/84263821/118388618-2a6b8980-b658-11eb-818e-5a2f65f12d1d.png)

**Comment by Oren-Hahiashvili** [comment]
Hi, thank you very much for your participation and for notifying me about the issue.
The issue will be fixed soon. If anyone can help with our bugs fix or improve the plugin, he is more than welcome.
Thank you very much for reporting about the issues.

**Comment by Oren-Hahiashvili** [comment]
> As shown in the image attached, the sticky header is blocking product quick view, currently using OceanWP theme with official Store demo.
> 
> ![image](https://user-images.githubusercontent.com/84263821/118388618-2a6b8980-b658-11eb-818e-5a2f65f12d1d.png)

Can you please check the version, if you think is working let me know, so i will update the wordpress repository.
